In [3]:
def isnum(n):
    n=str(n)
    if n.isdigit():
        return True
    return False
li=["10","20","a"]
a = map(isnum,li)
list(a)

[True, True, False]

In [4]:
a= filter(isnum,li)
list(a)

['10', '20']

### lambda

In [7]:
a = lambda x,y : x+y
a(9,8)

17

In [8]:
a= lambda x,y:x**y
a(3,6)

729

### list compherhension

In [9]:
a=int(input())
for i in range (0,a+1):
    print (i**2)

10
0
1
4
9
16
25
36
49
64
81
100


In [10]:
a=[i**2 for i in range(1,11)]
a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [16]:
a=[i**i for  i in range(1,5)]
a

[1, 4, 27, 256]

In [19]:
a=int(input())
f=1
for i in range(1,a+1):
    f=f*i
print(f)
    



5
120


In [25]:
f=1
f=[f*i for i in range(1,5]
f

[1, 2, 3, 4]

In [26]:
import math
s= [math.factorial(i) for i in range (1,10)]
s

[1, 2, 6, 24, 120, 720, 5040, 40320, 362880]

In [27]:
n=int (input())
m=10
l=[n*i for i in range (1,m+1)]
l

5


[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

## file handling
* performing operations on a fileis called file handling
* entering some data to a file iscalledas write to a file
* retreaving datafrom the fileis called readingfrom a file
* we can perform append ,delete operations on file.

In [39]:
def writetoafile(filename,data):
    with open(filename,"w") as f:
        f.write(data)
    return
filename="data.txt"
writetoafile(filename,"varuntej\n bhuvi\tmayank")

In [40]:
def readfromafile(filename):
    with open(filename,"r") as f:
        fd = f.read()
        f.close()
    return fd
readfromafile("data.txt")

'varuntej\n bhuvi\tmayank'

In [57]:
def readfromafile(filename):
    with open(filename,"r") as f:
        fd = f.read() 
        f.close()
    return fd
readfromafile("431.txt")
def printlines(filename):
    with open(fiilename,"r") as f:
        for line in f:
            print(line,end = "  ")
        return
#printlines(filename)
print(readfromafile(filename))

varuntej
 bhuvi	mayank


In [45]:
def readfromafile(filename):
    with open(filename,"r") as f:
        fd = f.read() 
        f.close()
    return fd
readfromafile("data.txt")
def printlines(filename):
    with open(fiilename,"r") as f:
        for line in f:
            print(line,end = "  ")
        return
#printlines(filename)
print(readfromafile(filename))        

varuntej
 bhuvi	mayank


In [47]:
def writetoafile(filename,data):
    with open(filename,"w") as f:
        f.write(data)
    return
filename="data.txt"
writetoafile(filename,
a=int(input())
f=1
for i in range(1,a+1):
    f=f*i
print(f))

SyntaxError: EOL while scanning string literal (<ipython-input-47-525217852462>, line 7)

In [50]:
def writetoafile(filename,data):
    with open(filename,"w") as f:
        f.write(data)
    return
filename="data.txt"
writetoafile(filename,"431.txt"    

SyntaxError: unexpected EOF while parsing (<ipython-input-50-69f72b58984d>, line 6)

In [52]:
def readfromafile(filename):
    with open(filename,"r") as f:
        fd = f.read()
        f.close()
    return fd
readfromafile("431.py")

'def isnum(n):\n    n=str(n)\n    if n.isdigit():\n        return True\n    return False\nli=["10","20","a"]\na = map(isnum,li)\nlist(a)'

In [1]:
def appendtofile(filename,data):
    with open(filename,"a") as f:
        for line in data:
            f.write("\n"+line)
        return
data=["line3","line4","line5"]
filename="data.txt"
appendtofile(filename,data)

# numpy

* no delay time
* numpyis an advanced library
* numpy...>numerical pyhon
* numpy isto perform athematical ,stastical operations
* the values are represented inthe form of rows andcolumns
* advantages of numpy
 *  uses less memory space,
 * time saving ,
 * Mbetter performance


In [2]:
import numpy as np

In [3]:
# creating an array using numpy
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
a.size

4

In [5]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(a)

numpy.ndarray

In [7]:
a+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
a-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
a*9

array([ 9, 18, 27, 36, 45, 54, 63, 72, 81])

## 

In [12]:
a2 =np.array([[1,2,3,4],[5,6,7,8]],dtype=complex)
a2

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j]])

In [14]:
np.arange

<function numpy.arange>

In [15]:
a.dtype

dtype('int32')

In [74]:
### comparision of two arrays

a1=print(np.arange([6]) + np.arange([7]))
a1

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [20]:
q=np.array([[1,2,3,4],[4,5,6,7]])
b=np.array([[4,5,6,7],[5,6,7,8]])

In [22]:
q+b

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15]])

In [23]:
q>b

array([[False, False, False, False],
       [False, False, False, False]])

In [24]:
q<b

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [25]:
q==b

array([[False, False, False, False],
       [False, False, False, False]])

In [26]:
q%3

array([[1, 2, 0, 1],
       [1, 2, 0, 1]], dtype=int32)

In [27]:
q**b

array([[      1,      32,     729,   16384],
       [   1024,   15625,  279936, 5764801]], dtype=int32)

In [33]:
np.ones(7,dtype=int)

array([1, 1, 1, 1, 1, 1, 1])

In [32]:
np.two(9)

AttributeError: module 'numpy' has no attribute 'two'

In [34]:
np.ones([5,5],dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
np.zeros([9,9],dtype=complex)

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j]])

In [37]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [43]:
a=[1,2,3,4]
a.append(5)

In [44]:
a

[1, 2, 3, 4, 5]

In [45]:
a =np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
a[0:1,1:2]

array([[2]])

In [47]:
a[1:2,2:3]

array([[7]])

In [48]:
a[:,1:3]

array([[2, 3],
       [6, 7]])

In [50]:
a[1:3,0:1]

array([[5]])

In [51]:
a[:,2:3]

array([[3],
       [7]])

In [52]:
a[2:3,:]

array([], shape=(0, 4), dtype=int32)

In [53]:
a[0:1,:]

array([[1, 2, 3, 4]])

In [55]:
a[:,0:2]

array([[1, 2],
       [5, 6]])

In [56]:
a[0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
a.shape

(2, 4)

In [58]:
a.ndim

2

In [61]:
a.itemsize

4

In [64]:
a.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [65]:
a.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [71]:
b=np.arange(3,5)
b

array([3, 4])

In [72]:
b.sort()

In [75]:
max(b)

4

In [76]:
np.std(b)

0.5

In [78]:
np.sum(b)

7

In [79]:
np.var(b)

0.25

In [80]:
np.cumsum(b)

array([3, 7], dtype=int32)

In [81]:
np.argmin(b)

0

In [82]:
np.argmax(b)

1

In [86]:
np.transpose(a)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [87]:
np.ravel(a)# changes do not save a=b



array([1, 2, 3, 4, 5, 6, 7, 8])

In [88]:
np.flaten(b)#changes done a=b

AttributeError: module 'numpy' has no attribute 'flaten'

In [1]:
b=int(input())
d=0
i=0
while b!=0:
    binary=b%10
    d=d+binary*(2**i)
    b=b//10
    i=i+1
print("decimal number is:",d)

100
decimal number is: 4


In [10]:
b=int(input())
s=0
while b>0:
    r=b%10
    s=s+r
    b=b//10
print("first digit is:",r)
print("last digit is:",s)

4685
first digit is: 4
last digit is: 23


In [17]:
def decimaltobinary(num):
    if num>1:
        decimaltobinary(num//2)
    print(num%2,end=" ")
    

In [13]:
b=4
bin(b)

'0b100'

In [21]:
a=56
bin(a)


TypeError: 'int' object is not subscriptable