### create afunction to find a perfect number
### create 3*3 array using range parameters

In [20]:
n=int(input("enter number"))
def perfectnumber(n):
    sum = 0
    for i in range(0,n):
        while f!= i:
            f=f/i
            sum=sum+f
perfectnumber(n)
if n==sum:
    print ("it is a perfect number:",n)
else :
    print("it is not a perfect number:",n)
   

NameError: name 'n' is not defined

if input is 6
output: factors of 6 is 1,2,3,6
    to be a perfect number = sum of the factors except itself
    1+2+3=6
    so 6 is to be a perfect number

In [7]:
import numpy 

In [9]:
a=numpy.array([[3,5,4,3,2,4,6,4,4],[4,5,3,2,5,3,2,4,5]])
a

array([[3, 5, 4, 3, 2, 4, 6, 4, 4],
       [4, 5, 3, 2, 5, 3, 2, 4, 5]])

In [12]:
a.reshape(3,3)

NameError: name 'a' is not defined

In [13]:
a=numpy.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:

a= numpy.arr

array([1, 9])